import { createError } from 'h3'
import type { MenuItem } from '~/types/menu'

const MENUS: Record<string, MenuItem[]> = {
  'main-menu': [
    {
      id: '1',
      name: 'Бургер «Классик»',
      price: 290,
      category: 'Бургеры',
      img: 'https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=1200&auto=format&fit=crop',
      tags: ['Хит'],
      description: 'Сочный говяжий котлет, фирменный соус и свежие овощи внутри мягкой булочки.',
      options: {
        sizes: [
          { label: 'Мал', add: 0 },
          { label: 'Стд', add: 40 },
          { label: 'Больш', add: 80 },
        ],
        extras: [
          { label: 'Сыр', add: 40 },
          { label: 'Бекон', add: 70 },
        ],
      },
    },
    {
      id: '2',
      name: 'Бургер «Острый»',
      price: 320,
      category: 'Бургеры',
      img: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?q=80&w=1200&auto=format&fit=crop',
      tags: ['Острый'],
      description: 'Пикантный бургер с халапеньо, острым соусом и двойной порцией сыра.',
    },
    {
      id: '13',
      name: 'Бургер «Дымный бекон»',
      price: 340,
      category: 'Бургеры',
      img: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?q=80&w=1200&auto=format&fit=crop',
      tags: ['Новинка'],
      description: 'Говяжья котлета, копчёный бекон и соус барбекю с хрустящим луком.',
    },
    {
      id: '14',
      name: 'Бургер «Гриль-овощи»',
      price: 310,
      category: 'Бургеры',
      img: 'https://images.unsplash.com/photo-1508737804141-4c3b688e2546?q=80&w=1200&auto=format&fit=crop',
      tags: ['Вегетарианский'],
      description: 'Котлета из нута, овощи гриль и крем-чиз на тёплой булочке.',
    },
    {
      id: '15',
      name: 'Бургер «Трюфельный»',
      price: 390,
      category: 'Бургеры',
      img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop',
      tags: ['Премиум'],
      description: 'Мраморная говядина, трюфельный айоли и карамелизированный лук.',
    },
    {
      id: '3',
      name: 'Картофель фри',
      price: 120,
      category: 'Закуски',
      img: 'https://images.unsplash.com/photo-1541592553160-82008b127ccb?q=80&w=1200&auto=format&fit=crop',
      tags: ['Веган'],
      description: 'Хрустящий картофель, обжаренный во фритюре до золотистой корочки.',
      options: {
        sizes: [
          { label: 'Мал', add: 0 },
          { label: 'Больш', add: 50 },
        ],
      },
    },
    {
      id: '16',
      name: 'Куриные наггетсы',
      price: 210,
      category: 'Закуски',
      img: 'https://images.unsplash.com/photo-1608032369783-260b4b31f4a6?q=80&w=1200&auto=format&fit=crop',
      tags: ['Хит'],
      description: 'Золотистые кусочки курицы с соусом на выбор.',
    },
    {
      id: '17',
      name: 'Начос с сыром',
      price: 230,
      category: 'Закуски',
      img: 'https://images.unsplash.com/photo-1514996937319-344454492b37?q=80&w=1200&auto=format&fit=crop',
      tags: ['Под фильм'],
      description: 'Хрустящие начос с расплавленным сыром и соусом сальса.',
    },
    {
      id: '18',
      name: 'Креветки темпура',
      price: 280,
      category: 'Закуски',
      img: 'https://images.unsplash.com/photo-1604908177023-3be3d325770b?q=80&w=1200&auto=format&fit=crop',
      tags: ['С хрустом'],
      description: 'Сочные креветки в кляре с соусом терияки.',
    },
    {
      id: '4',
      name: 'Салат «Цезарь»',
      price: 260,
      category: 'Салаты',
      img: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?q=80&w=1200&auto=format&fit=crop',
      tags: [],
      description: 'Классический салат с соусом цезарь, курицей и пармезаном.',
    },
    {
      id: '19',
      name: 'Салат с киноа и авокадо',
      price: 310,
      category: 'Салаты',
      img: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?q=80&w=1200&auto=format&fit=crop',
      tags: ['Полезно'],
      description: 'Киноа, авокадо и шпинат с лимонной заправкой.',
    },
    {
      id: '20',
      name: 'Греческий салат',
      price: 280,
      category: 'Салаты',
      img: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1200&auto=format&fit=crop',
      tags: ['Классика'],
      description: 'Помидоры, огурцы, оливки и фета с орегано.',
    },
    {
      id: '21',
      name: 'Салат с уткой и апельсином',
      price: 350,
      category: 'Салаты',
      img: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?q=80&w=1200&auto=format&fit=crop',
      tags: ['Празднично'],
      description: 'Тёплая утка, цитрусовая заправка и карамелизированные орехи.',
    },
    {
      id: '5',
      name: 'Лимонад домашний',
      price: 110,
      category: 'Напитки',
      img: 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?q=80&w=1200&auto=format&fit=crop',
      tags: [],
      description: 'Освежающий напиток с лимоном, мятой и лёгкой кислинкой.',
      options: {
        sizes: [
          { label: '300 мл', add: 0 },
          { label: '500 мл', add: 30 },
        ],
      },
    },
    {
      id: '22',
      name: 'Имбирный чай с облепихой',
      price: 160,
      category: 'Напитки',
      img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop',
      tags: ['Согревает'],
      description: 'Ароматный чай с облепихой, имбирём и мёдом.',
    },
    {
      id: '23',
      name: 'Чай «Ягодный сад»',
      price: 150,
      category: 'Напитки',
      img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop',
      tags: ['Без сахара'],
      description: 'Микс малины, смородины и каркаде с лёгкой кислинкой.',
    },
    {
      id: '24',
      name: 'Холодный чай с персиком',
      price: 170,
      category: 'Напитки',
      img: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?q=80&w=1200&auto=format&fit=crop',
      tags: ['Освежает'],
      description: 'Пряный холодный чай с персиком и мятой.',
    },
    {
      id: '6',
      name: 'Пицца Маргарита',
      price: 490,
      category: 'Пицца',
      img: 'https://images.unsplash.com/photo-1548365328-9f547fb095c3?q=80&w=1200&auto=format&fit=crop',
      tags: ['Хит'],
      description: 'Тонкое тесто, томатный соус, моцарелла и свежий базилик.',
      options: {
        sizes: [
          { label: '25 см', add: 0 },
          { label: '30 см', add: 120 },
          { label: '35 см', add: 220 },
        ],
        extras: [
          { label: 'Пепперони', add: 120 },
          { label: 'Сыр Моцарелла', add: 90 },
        ],
      },
    },
    {
      id: '25',
      name: 'Пицца «Четыре сыра»',
      price: 520,
      category: 'Пицца',
      img: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=1200&auto=format&fit=crop',
      tags: ['Хит'],
      description: 'Моцарелла, горгонзола, пармезан и эмменталь на тонком тесте.',
    },
    {
      id: '26',
      name: 'Пицца «Пепперони»',
      price: 510,
      category: 'Пицца',
      img: 'https://images.unsplash.com/photo-1548365328-9f547fb095c3?q=80&w=1200&auto=format&fit=crop',
      tags: ['Пикантно'],
      description: 'Обилие пепперони, томатный соус и тянущийся сыр.',
    },
    {
      id: '27',
      name: 'Пицца «Вегетариана»',
      price: 480,
      category: 'Пицца',
      img: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?q=80&w=1200&auto=format&fit=crop',
      tags: ['Веган'],
      description: 'Сладкий перец, грибы, оливки и артишоки на томатном соусе.',
    },
    {
      id: '7',
      name: 'Паста Карбонара',
      price: 380,
      category: 'Паста',
      img: 'https://images.unsplash.com/photo-1523986371872-9d3ba2e2f642?q=80&w=1200&auto=format&fit=crop',
      tags: [],
      description: 'Классическая паста с беконом, сливочным соусом и пармезаном.',
    },
    {
      id: '28',
      name: 'Паста «Песто»',
      price: 360,
      category: 'Паста',
      img: 'https://images.unsplash.com/photo-1516100882582-96c3a05fe590?q=80&w=1200&auto=format&fit=crop',
      tags: ['Лёгко'],
      description: 'Тальятелле с соусом песто, томатами и кедровыми орешками.',
    },
    {
      id: '29',
      name: 'Паста с морепродуктами',
      price: 420,
      category: 'Паста',
      img: 'https://images.unsplash.com/photo-1512058564366-c9e4c3edaccd?q=80&w=1200&auto=format&fit=crop',
      tags: ['Море'],
      description: 'Лингвини с креветками, мидиями и соусом из белого вина.',
    },
    {
      id: '30',
      name: 'Паста с грибами и сливками',
      price: 350,
      category: 'Паста',
      img: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?q=80&w=1200&auto=format&fit=crop',
      tags: ['Сытно'],
      description: 'Фетуччине с шампиньонами и сливочным соусом.',
    },
    {
      id: '8',
      name: 'Чизкейк Нью-Йорк',
      price: 220,
      category: 'Десерты',
      img: 'https://images.unsplash.com/photo-1505253216365-9b094d542965?q=80&w=1200&auto=format&fit=crop',
      tags: ['Новинка'],
      description: 'Нежный сливочный чизкейк на песочной основе с ванилью.',
    },
    {
      id: '31',
      name: 'Тирамису классический',
      price: 250,
      category: 'Десерты',
      img: 'https://images.unsplash.com/photo-1523986371872-9d3ba2e2f642?q=80&w=1200&auto=format&fit=crop',
      tags: ['Италия'],
      description: 'Воздушный крем маскарпоне, пропитанные савоярди и какао.',
    },
    {
      id: '32',
      name: 'Мусс из маракуйи',
      price: 230,
      category: 'Десерты',
      img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop',
      tags: ['Тропики'],
      description: 'Лёгкий мусс с маракуйей и хрустящей крошкой.',
    },
    {
      id: '33',
      name: 'Шоколадный фондан',
      price: 260,
      category: 'Десерты',
      img: 'https://images.unsplash.com/photo-1548365328-9f547fb095c3?q=80&w=1200&auto=format&fit=crop',
      tags: ['Горячее'],
      description: 'Тёплый десерт с жидкой шоколадной начинкой и мороженым.',
    },
    {
      id: '9',
      name: 'Том-ям с креветками',
      price: 360,
      category: 'Супы',
      img: 'https://images.unsplash.com/photo-1553621042-f6e147245754?q=80&w=1200&auto=format&fit=crop',
      tags: ['Пикантно'],
      description: 'Ароматный тайский суп с кокосовым молоком, креветками и лимонграссом.',
      options: {
        extras: [
          { label: 'Дополнительные креветки', add: 90 },
          { label: 'Рис жасмин', add: 70 },
        ],
      },
    },
    {
      id: '34',
      name: 'Крем-суп из тыквы',
      price: 250,
      category: 'Супы',
      img: 'https://images.unsplash.com/photo-1543353071-873f17a7a088?q=80&w=1200&auto=format&fit=crop',
      tags: ['Осень'],
      description: 'Пюре из тыквы с кокосовым молоком и жареными семечками.',
    },
    {
      id: '35',
      name: 'Рамен с говядиной',
      price: 390,
      category: 'Супы',
      img: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?q=80&w=1200&auto=format&fit=crop',
      tags: ['Азия'],
      description: 'Насыщенный бульон, лапша и маринованное яйцо.',
    },
    {
      id: '36',
      name: 'Суп минестроне',
      price: 280,
      category: 'Супы',
      img: 'https://images.unsplash.com/photo-1543332164-6e82f355bad0?q=80&w=1200&auto=format&fit=crop',
      tags: ['Легко'],
      description: 'Овощи, фасоль и томатный бульон с травами.',
    },
    {
      id: '10',
      name: 'Боул с лососем и киноа',
      price: 420,
      category: 'Боулы',
      img: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=1200&auto=format&fit=crop',
      tags: ['Полезно'],
      description: 'Питательный боул с маринованным лососем, киноа и свежими овощами.',
    },
    {
      id: '37',
      name: 'Боул с тофу и овощами',
      price: 360,
      category: 'Боулы',
      img: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=1200&auto=format&fit=crop',
      tags: ['Веган'],
      description: 'Тофу, коричневый рис, свежие овощи и соус терияки.',
    },
    {
      id: '38',
      name: 'Боул с говядиной терияки',
      price: 410,
      category: 'Боулы',
      img: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?q=80&w=1200&auto=format&fit=crop',
      tags: ['Сытно'],
      description: 'Маринованная говядина, рис и овощи под сладковатым соусом.',
    },
    {
      id: '39',
      name: 'Боул с креветками и манго',
      price: 430,
      category: 'Боулы',
      img: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=1200&auto=format&fit=crop',
      tags: ['Лето'],
      description: 'Сладкий манго, креветки и рис жасмин с лаймовой заправкой.',
    },
    {
      id: '11',
      name: 'Круассан с ветчиной и сыром',
      price: 210,
      category: 'Завтраки',
      img: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?q=80&w=1200&auto=format&fit=crop',
      tags: ['Утром'],
      description: 'Слоёный круассан с сочной ветчиной, сыром и сливочным соусом.',
    },
    {
      id: '40',
      name: 'Овсянка с ягодами',
      price: 190,
      category: 'Завтраки',
      img: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1c0?q=80&w=1200&auto=format&fit=crop',
      tags: ['Полезно'],
      description: 'Овсяная каша на миндальном молоке с сезонными ягодами.',
    },
    {
      id: '41',
      name: 'Сырники с сметаной',
      price: 210,
      category: 'Завтраки',
      img: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?q=80&w=1200&auto=format&fit=crop',
      tags: ['Домашнее'],
      description: 'Нежные сырники из фермерского творога со сметаной и мёдом.',
    },
    {
      id: '42',
      name: 'Яичница с овощами на гриле',
      price: 220,
      category: 'Завтраки',
      img: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?q=80&w=1200&auto=format&fit=crop',
      tags: ['Сытно'],
      description: 'Яичница-глазунья с томатами, шпинатом и сливочным соусом.',
    },
    {
      id: '12',
      name: 'Матча латте',
      price: 190,
      category: 'Кофе и чай',
      img: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=1200&auto=format&fit=crop',
      tags: ['Без сахара'],
      description: 'Кремовый латте на основе матча с миндальным молоком.',
      options: {
        sizes: [
          { label: '250 мл', add: 0 },
          { label: '400 мл', add: 40 },
        ],
        extras: [
          { label: 'Сироп ваниль', add: 30 },
          { label: 'Взбитые сливки', add: 40 },
        ],
      },
    },
    {
      id: '43',
      name: 'Раф ванильно-карамельный',
      price: 210,
      category: 'Кофе и чай',
      img: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=1200&auto=format&fit=crop',
      tags: ['Сладко'],
      description: 'Кофейный напиток с ванильно-карамельным сиропом и сливками.',
    },
    {
      id: '44',
      name: 'Капучино на овсяном молоке',
      price: 200,
      category: 'Кофе и чай',
      img: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=1200&auto=format&fit=crop',
      tags: ['Без лактозы'],
      description: 'Нежный капучино на овсяном молоке с корицей.',
    },
    {
      id: '45',
      name: 'Чай латте с чёрной смородиной',
      price: 195,
      category: 'Кофе и чай',
      img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop',
      tags: ['Ягоды'],
      description: 'Пряный чай латте с чёрной смородиной и сливочной пеной.',
    },
  ],
  'letnee-menu': [
    {
      id: '1',
      name: 'Гаспачо арбузный',
      price: 240,
      category: 'Холодные супы',
      img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200&auto=format&fit=crop',
      tags: ['Сезон'],
      description: 'Лёгкий холодный суп из арбуза, томатов и огурцов с каплей оливкового масла.',
      options: {
        extras: [
          { label: 'Креветки', add: 120 },
        ],
      },
    },
    {
      id: '2',
      name: 'Салат с клубникой и шпинатом',
      price: 290,
      category: 'Салаты',
      img: 'https://images.unsplash.com/photo-1463740839922-2d3b7e426a56?q=80&w=1200&auto=format&fit=crop',
      tags: ['Веган'],
      description: 'Свежая клубника, шпинат и фета с лёгкой цитрусовой заправкой.',
    },
    {
      id: '3',
      name: 'Сэндвич с курицей и манго',
      price: 310,
      category: 'Закуски',
      img: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=1200&auto=format&fit=crop',
      tags: ['Новинка'],
      description: 'Тёплый сэндвич с курицей, манго и пикантным соусом карри.',
    },
    {
      id: '4',
      name: 'Лимонад с маракуйей',
      price: 180,
      category: 'Напитки',
      img: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?q=80&w=1200&auto=format&fit=crop',
      tags: ['Хит'],
      description: 'Искристый лимонад с мякотью маракуйи и ароматом мяты.',
      options: {
        sizes: [
          { label: '350 мл', add: 0 },
          { label: '500 мл', add: 40 },
        ],
      },
    },
    {
      id: '5',
      name: 'Мороженое с базиликом и лаймом',
      price: 210,
      category: 'Десерты',
      img: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?q=80&w=1200&auto=format&fit=crop',
      tags: [],
      description: 'Домашнее мороженое с нотами базилика и лаймовой свежести.',
    },
    {
      id: '6',
      name: 'Овощи гриль с халлуми',
      price: 330,
      category: 'Гриль',
      img: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?q=80&w=1200&auto=format&fit=crop',
      tags: ['Лето'],
      description: 'Тёплая тарелка из цуккини, перца и халлуми с соусом песто.',
    },
    {
      id: '7',
      name: 'Смузи «Тропический бриз»',
      price: 260,
      category: 'Смузи',
      img: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?q=80&w=1200&auto=format&fit=crop',
      tags: ['Освежает'],
      description: 'Смузи из ананаса, манго и кокосовой воды с мятой.',
      options: {
        extras: [
          { label: 'Чиа', add: 25 },
          { label: 'Протеин', add: 45 },
        ],
      },
    },
  ],
  'corporate-packages': [
    {
      id: '1',
      name: 'Сет «Офисный»',
      price: 4900,
      category: 'Наборы',
      img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200&auto=format&fit=crop',
      tags: ['Для команды'],
      description: 'Готовый обед для команды до десяти человек с горячими блюдами и закусками.',
    },
    {
      id: '2',
      name: 'Сет «Фуршет»',
      price: 7200,
      category: 'Наборы',
      img: 'https://images.unsplash.com/photo-1543353071-10c8ba85a904?q=80&w=1200&auto=format&fit=crop',
      tags: ['Премиум'],
      description: 'Ассорти канапе, мини-десертов и напитков для статусных мероприятий.',
    },
    {
      id: '3',
      name: 'Кофе-брейк «Утро»',
      price: 2600,
      category: 'Напитки и десерты',
      img: 'https://images.unsplash.com/photo-1495744472287-4d71bcdd2085?q=80&w=1200&auto=format&fit=crop',
      tags: [],
      description: 'Горячий кофе, выпечка и лёгкие десерты для продуктивного утра.',
      options: {
        extras: [
          { label: 'Фрукты', add: 600 },
        ],
      },
    },
    {
      id: '4',
      name: 'Ланч-боксы персональные',
      price: 540,
      category: 'Персональные наборы',
      img: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c7?q=80&w=1200&auto=format&fit=crop',
      tags: ['Популярно'],
      description: 'Индивидуальные наборы с горячим блюдом, гарниром и салатом.',
      options: {
        sizes: [
          { label: 'Стандарт', add: 0 },
          { label: 'Расширенный', add: 180 },
        ],
      },
    },
    {
      id: '5',
      name: 'Фуршет «Вечер в городе»',
      price: 8900,
      category: 'Праздничные наборы',
      img: 'https://images.unsplash.com/photo-1547919307-1ecb10702e11?q=80&w=1200&auto=format&fit=crop',
      tags: ['Событие'],
      description: 'Разнообразные мини-бургеры, тарталетки и десерты для вечерних мероприятий.',
      options: {
        extras: [
          { label: 'Официант на мероприятие', add: 2500 },
        ],
      },
    },
    {
      id: '6',
      name: 'Десертный стол «Sweet Break»',
      price: 3600,
      category: 'Десерты',
      img: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop',
      tags: ['Для кофе-брейка'],
      description: 'Набор из пирожных, маффинов и фруктов для уютного перерыва.',
    },
  ],
}

export default defineEventHandler((event) => {
  const slug = event.context.params?.slug
  if (!slug || typeof slug !== 'string') {
    throw createError({
      statusCode: 400,
      statusMessage: 'Неверный идентификатор меню',
    })
  }

  const menu = MENUS[slug]

  if (!menu) {
    throw createError({
      statusCode: 404,
      statusMessage: 'Меню не найдено',
    })
  }

  return menu
})
